#%RAML 1.0
---
title: Individuals Expenses (MTD)
description: Retrieve, amend and delete employment and other expenses, and ignore employment expenses provided by HMRC.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

mediaType: application/hal+json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml
  queryParameters: queryParameters.raml

'/individuals/expenses':
  /other:
    /{nino}:
      uriParameters:
        nino:
          description: National Insurance number, in the format AA999999A.
          type: string
          example: TC663795B
      /{taxYear}:
        uriParameters:
          taxYear:
            description: 'The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2020-22 is not valid. (The minimum tax year in Sandbox is 2019-20.)'
            example: "2020-21"
        put: !include amend_other_expenses.raml
        get: !include retrieve_other_expenses.raml
        delete: !include delete_other_expenses.raml
  /employments:
    /{nino}:
      uriParameters:
        nino:
          description: National Insurance number, in the format AA999999A.
          type: string
          example: TC663795B
      /{taxYear}:
        uriParameters:
          taxYear:
            description: 'The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. The minimum tax year is 2021-22. No gaps are allowed, for example, 2020-22 is not valid. (The minimum tax year in Sandbox is 2019-20.)'
            example: "2021-22"
        put: !include amend_employment_expenses.raml
        get: !include retrieve_employment_expenses.raml
        delete: !include delete_employment_expenses.raml
        /ignore:
          put: !include ignore_employment_expenses.raml