summary: Retrieve Employment Expenses
description: |
  This endpoint enables you to retrieve existing employment expenses.
  A National Insurance number and tax year must be provided.
  
  ### Test data
  Scenario simulations using Gov-Test-Scenario headers are available only in the sandbox environment.
  
  | Header Value (Gov-Test-Scenario)        | Scenario                                                                                                                                                              |
  | --------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
  | N/A - DEFAULT <br> **?source=user**     | Requesting **user** source simulates success response with User provided financial details.                                                                           |
  | N/A - DEFAULT <br> **?source=hmrcHeld** | Requesting **hmrcHeld** source simulates success response with HMRC held financial details.                                                                           |
  | N/A - DEFAULT <br> **?source=latest**   | Requesting **latest** source simulates success response with Latest financial details submitted.                                                                      |
  | NOT_FOUND                               | Simulates the scenario where no data is found.                                                                                                                        |
  | STATEFUL                                | Performs a stateful retrieve.                                                                                                                                         |
  | DYNAMIC                                 | The following response values will change to correspond to the values submitted in the request: <br/> &bull; source <br/> &bull; submittedOn <br/> &bull; dateIgnored |


tags:
  - Employment Expenses

parameters:
  - $ref: './common/pathParameters.yaml#/components/parameters/nino'
  - $ref: './common/pathParameters.yaml#/components/parameters/taxYear'
  - $ref: './common/queryParameters.yaml#/components/parameters/source'
  - $ref: './common/headers.yaml#/components/parameters/acceptHeader'
  - $ref: './common/headers.yaml#/components/parameters/authorizationReadScopeHeader'
  - $ref: './common/headers.yaml#/components/parameters/testScenarioHeader'

security:
  - User-Restricted:
      - read:self-assessment

responses:
  "200":
    description: Success
    headers:
      X-CorrelationId:
        $ref: './common/headers.yaml#/components/parameters/correlationId'
    content:
      application/json:
        schema:
          $ref: './schemas/retrieve_employment_expenses_response.json'
        examples:
          example-1:
            description: Example user response
            value:
              $ref: './examples/retrieve_employment_expenses/user.json'
          example-2:
            description: Example hmrcHeld response
            value:
              $ref: './examples/retrieve_employment_expenses/hmrc_held.json'
          example-3:
            description: Example latest response
            value:
              $ref: './examples/retrieve_employment_expenses/latest.json'

  "400":
    description: Bad request
    content:
      application/json:
        schema:
          $ref: './schemas/error-response.yaml'
        examples:
          FORMAT_NINO:
            $ref: './common/errors.yaml#/components/examples/formatNino'
          FORMAT_TAX_YEAR:
            $ref: './common/errors.yaml#/components/examples/formatTaxYear'
          FORMAT_TAX_SOURCE:
            $ref: './common/errors.yaml#/components/examples/formatSource'
          RULE_TAX_YEAR_NOT_SUPPORTED:
            $ref: './common/errors.yaml#/components/examples/ruleTaxYearNotSupported'
          RULE_TAX_YEAR_RANGE_INVALID:
            $ref: './common/errors.yaml#/components/examples/ruleTaxYearRangeInvalid'
          RULE_INCORRECT_GOV_TEST_SCENARIO:
            $ref: './common/errors.yaml#/components/examples/ruleIncorrectGovTestScenario'

  "403":
    description: Forbidden
    content:
      application/json:
        schema:
          $ref: './schemas/error-response.yaml'
        examples:
          CLIENT_OR_AGENT_NOT_AUTHORISED:
            $ref: './common/errors.yaml#/components/examples/clientOrAgentNotAuthorised'

  "404":
    description: Not Found
    content:
      application/json:
        schema:
          $ref: './schemas/error-response.yaml'
        examples:
          MATCHING_RESOURCE_NOT_FOUND:
            $ref: './common/errors.yaml#/components/examples/notFound'
